services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dancer-app:latest
    volumes:
      - .:/app
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    environment:
      PLACK_ENV: development
